# -- Generated by bubble with <3. --

suppressPackageStartupMessages({
  require(tidyverse)
  require(ggplot)
})

# source('file')

if(interactive()){
  .args <-  c('data/raw/rt.csv',
              'data/raw/rt.csv',
              'data/raw/rt.csv',
              'data/raw/rt.csv',
              'plot.png')
} else {
  .args <- commandArgs(trailingOnly = T)
}


data <- read_csv(.args[1])

p <- data %>%
  ggplot() +
  geom_path(aes(x = date, y = confirm))

ggsave(tail(.args, 1),
       p,
       width = 8.5, height = 6,
       units = 'in')

ggsave(gsub('.png', '.pdf', tail(.args, 1)),
       p,
       width = 8.5, height = 6,
       units = 'in',
       useDingbats = F)
